@host = http://localhost:8090
@baseAuth = {{host}}/api/auth
@usernameUser = user.jwt
@passwordUser = user12345
@usernameAdmin = admin.jwt
@passwordAdmin = admin12345

### Registro de usuario ROLE_USER (por defecto)
POST {{baseAuth}}/register
Content-Type: application/json

{
  "username": "{{usernameUser}}",
  "password": "{{passwordUser}}",
  "enabled": true
}

### Login USER (guardar token en variable global userToken)
POST {{baseAuth}}/login
Content-Type: application/json

{
  "username": "{{usernameUser}}",
  "password": "{{passwordUser}}"
}

> {%
client.global.set("userToken", response.body.token);
%}

### Registro de usuario para pruebas "ADMIN" (register ignora rolIds)

## NOTA: /api/auth/register no procesa "rolIds" del body (no existe en RegisterRequest).
## Siempre asigna el rol por defecto ROLE_USER en AuthServiceImpl.
## Si necesitas probar flujos ADMIN, cambia la tabla usuario_rol manualmente o usa un usuario ADMIN existente.
POST {{baseAuth}}/register
Content-Type: application/json

{
  "username": "{{usernameAdmin}}",
  "password": "{{passwordAdmin}}",
  "enabled": true,
}

### Login ADMIN (guardar token en variable global adminToken)
POST {{baseAuth}}/login
Content-Type: application/json

{
  "username": "{{usernameAdmin}}",
  "password": "{{passwordAdmin}}"
}

> {%
client.global.set("adminToken", response.body.token);
%}

