@host = http://localhost:8090
@api = {{host}}/api
@ts = {{$timestamp}}
@rolAdminId = 1
@testCategoria = Cat.Seguridad.{{ts}}
@userUsername = user.seg.1771408872
@userPassword = user12345
@adminUsername = admin.seg.1771408922
@adminPassword = admin12345
@userToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyLnNlZy4xNzcxNDA4ODcyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTc3MTQxMDA4OCwiZXhwIjoxNzcxNDEzNjg4fQ.mf2_r4M1lsqOJjszIBR5BSFSI_eQh6A0beEAbypjQi4
@adminToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbi5zZWcuMTc3MTQwODkyMiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzcxNDEwMzYwLCJleHAiOjE3NzE0MTM5NjB9.DFqt5vw6wLcH9MwNhkoSoXa7ijbTEZDL_gmGF1DADz8

### 0) Acceso sin token -> 401
GET {{api}}/categorias
Content-Type: application/json

### 1) Registro USER (rol por defecto ROLE_USER)
POST {{api}}/auth/register
Content-Type: application/json

{
  "username": "{{userUsername}}",
  "password": "{{userPassword}}",
  "enabled": true
}

### 2) Registro ADMIN (ajusta rolAdminId si en tu BD no es 1)
POST {{api}}/auth/register
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}",
  "enabled": true,
  "rolIds": [{{rolAdminId}}]
}

### 3) Login USER y guardar token global userToken
POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "{{userUsername}}",
  "password": "{{userPassword}}"
}

> {%
client.global.set("userToken", response.body.token);
%}

### 4) Login ADMIN y guardar token global adminToken
POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {%
client.global.set("adminToken", response.body.token);
%}

### 5) USER puede consultar catalogo -> 200
GET {{api}}/categorias?sort=id,asc&page=0&size=5
Authorization: Bearer {{userToken}}
Content-Type: application/json

### 6) USER no puede crear categoria -> 403
POST {{api}}/categorias
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "nombre": "{{testCategoria}}",
  "descripcion": "Debe fallar con ROLE_USER"
}

### 7) ADMIN puede crear categoria -> 200
POST {{api}}/categorias
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "nombre": "{{testCategoria}}",
  "descripcion": "Creada por ROLE_ADMIN"
}

### 8) USER no puede gestionar usuarios -> 403
GET {{api}}/usuarios?sort=id,asc&page=0&size=5
Authorization: Bearer {{userToken}}
Content-Type: application/json

### 9) ADMIN si puede gestionar usuarios -> 200
GET {{api}}/usuarios?sort=id,asc&page=0&size=5
Authorization: Bearer {{adminToken}}
Content-Type: application/json

### 10) USER puede crear alquiler -> 200
POST {{api}}/alquileres
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "fechaInicio": "2026-03-01",
  "fechaFin": "2026-03-03",
  "precioTotal": 150.00,
  "clienteId": 1,
  "vehiculoId": 1
}

### 11) USER no puede eliminar alquiler -> 403
DELETE {{api}}/alquileres/1
Authorization: Bearer {{userToken}}
Content-Type: application/json

### 12) Credenciales invalidas -> 401
POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "no-existe",
  "password": "wrong-pass"
}
